Homework - 14
kvartalshow/beetroot pull request #14
Opened 2020-11-04 16:58 UTC by kvartalshow

2020-11-07 13:02 UTC, a1exalexander requested changes
Почитать про БЕМ и все исправить
ссылки в ПР #12 

и предалть другие элементы по БЕМУ
`<li class="header__menu-nav-item">Services</li>` => `<li class="nav__item"><a href='...' class="nav-link">Services</a></li>`

и постарайся делать пиксель перфект
- размеры кнопок проверь 
- растояния между элементами
- line-height текстов
 например у тебя в разделе Contacts вообщзе не такие растояния между строками Их вообще нет
![image](https://user-images.githubusercontent.com/40409129/98441922-27706900-210a-11eb-9f83-edee9e60b1b2.png)

![image](https://user-images.githubusercontent.com/40409129/98441937-47079180-210a-11eb-8a21-758a3a8abf97.png)

якоря не работают

2020-11-07 13:02 UTC, a1exalexander commented on hw-14/src/scss/components/_about.scss
> +        &-title{
ТАК делать НЕЛЬЗЯ
https://nicothin.pro/idiomatic-pre-CSS/#amp

> Никогда не используйте амперсанд в местах разделения словосочетаний имён блоков, элементов или модификаторов (см. пример).
> Никогда не повторяйте написанный с амперсандом селектор внутри одного контекста.

2020-11-07 13:03 UTC, a1exalexander commented
+ конфликты

2020-11-12 07:03 UTC, kvartalshow commented on hw-14/src/scss/components/_about.scss
> +        &-title{
:0
  Понял

2020-11-12 22:00 UTC, kvartalshow commented on hw-14/src/scss/components/_about.scss
> +        &-title{
Кнопки были в порядке ))0

2020-12-12 11:27 UTC, merged